### ISSUE TITLE
Is the global elisp-koans-a use intentional in elisp-koans/special-forms-cond ()?

### ISSUE THREAD

**Issue by jchochli** [jtmoulia/elisp-koans#10]
https://github.com/jtmoulia/elisp-koans/blob/e809ccce03a4d58071d30b95f56c99bf50322404/koans/special-forms.el#L166

a is bound in let* first and then elisp-koans-a is used in cond instead of a.

`(let* ((a 4)
        (c (cond ((> elisp-koans-a 0) :positive)
                 ((< elisp-koans-a 0) :negative)
 `

**Comment by jtmoulia** [comment]
That is indeed a bug! Thanks for calling it out @jchochli 

If you're interested you're welcome to fix it in a PR. Otherwise, let me know and I'm happy to clean it up.

Cheers

**Comment by jchochli** [comment]
Okay I'll submit a PR, thanks.

Separately, I think the docstring for equality-distinctions.el elisp-koans/equality-distinctions-test-string-equal () is incorrect: "string-equal is just like string= **except that differences in case are ignored.**"

Based on the test results, and help says string= is an alias for ‘string-equal’, both say 'Case is significant.'  If that's true, Should I include a change in that docstring or should I create a new issue for that?

**Comment by jtmoulia** [comment]
Yes, that would also be good to fix -- good catch! Looks like that's a difference between Emacs and Common Lisp.

Feel free to include it in the same PR -- it's a small change and this lib is still young.
