### ISSUE TITLE
Using `cl-lib` over `cl`

### ISSUE THREAD

**Issue by juxd** [jtmoulia/elisp-koans#14]
Hello, thanks for the awesome tutorial!

When editing and running this, my Emacs keeps warning about the deprecation of `cl` library, instead suggesting to use `cl-lib`. GNU's Emacs Common Lisp Emulation [documentation](https://www.gnu.org/software/emacs/manual/html_node/cl/Organization.html) also seems to suggest likewise. 

Should we follow this convention? There is an annoying side effect of prefixing every macro usage with `cl-`

**Comment by jtmoulia** [comment]
Yup, resolved by #16 though the change hasn't been packaged up in its own release.

Closing this issue.
