### ISSUE TITLE
Incomplete name in evaluation.el (test-quoting-behavior)

### ISSUE THREAD

**Issue by argvniyx** [jtmoulia/elisp-koans#6]
First off, great stuff! Thanks for taking the time to do this.

I was going through the koans and I realized that in ```evaluation.el```, the last test is named ```test-quoting-behavior``` instead of ```elisp-koans/test-quoting-behavior```. Is this intentional? I run the tests using ```M-x [name of test]``` and therefore find myself using ```M-p``` to travel back in history, which kinda bit me doing this koan because I missed that it was named differently. It does run without problems, but I figured that if this wasn't intentional, pointing it out would be nice so that other people have a frictionless experience, and so that it would remain consistent.

**Comment by argvniyx** [comment]
I have also found a typo in ```special-forms.el```.

    (elisp-koans/deftest
     elisp-koans/spcial-forms-let-default-value ()

Should be `special` instead of `spcial`

**Comment by jtmoulia** [comment]
Awesome @argvniyx! I pushed some fixes for the issues you've highlighted -- much appreciated.
